WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1052205b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1052209a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105221090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101534640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1015348b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101534fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105a6c610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105a6c880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105a6cf70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1033f05e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1033f0850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1033f0f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1021750c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1021753f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102175c30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102175d80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102175000>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102175570>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176410>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102174df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176b30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102177130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176c80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102177850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102177be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102177ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102177970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1021762f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1021774f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176c20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176ec0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176d40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102175f60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102177a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176b00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x102176c20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e750c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e753f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e75c30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e75780>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101b21450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e74e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76410>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76b30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76c80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77100>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e778b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76410>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76aa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e76530>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e77b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e753f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e75000>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101e75c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x101ef84c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/getMe
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105d8c610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105d8c880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105d8cf70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105d8d2a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105d8d420>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x105d8d5a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /bot5955607641:AAEy5DlDL_7G4FqBlreqq5f4c665RXxywd0/sendDocument
